package cdk


// Level of tsconfig validation jsii should perform.
// Experimental.
type ValidateTsconfig string

const (
	// Validates against a strict rule set designed for widespread support and backwards-compatibility.
	// Experimental.
	ValidateTsconfig_STRICT ValidateTsconfig = "STRICT"
	// Enforces a tsconfig as if it were generated by jsii.
	// Experimental.
	ValidateTsconfig_GENERATED ValidateTsconfig = "GENERATED"
	// Only reject options known to be incompatible with jsii.
	// Experimental.
	ValidateTsconfig_MINIMAL ValidateTsconfig = "MINIMAL"
	// Disables all config validation.
	//
	// Use at your own risk.
	// Experimental.
	ValidateTsconfig_OFF ValidateTsconfig = "OFF"
)

