package projen


// Schema for `tasks.json`.
// Experimental.
type TasksManifest struct {
	// Environment for all tasks.
	// Experimental.
	Env *map[string]*string `field:"optional" json:"env" yaml:"env"`
	// The version of the tasks manifest schema.
	//
	// Used by the task runtime to detect manifests produced by a newer version
	// of projen. Manifests generated by older versions of projen omit this field
	// and are treated as "legacy" for backwards compatibility.
	// Default: - the manifest is treated as a legacy (unversioned) manifest.
	//
	// Experimental.
	ManifestVersion *float64 `field:"optional" json:"manifestVersion" yaml:"manifestVersion"`
	// All tasks available for this project.
	// Experimental.
	Tasks *map[string]*TaskSpec `field:"optional" json:"tasks" yaml:"tasks"`
}

