package javascript


// Experimental.
type NodeConfigSchemaNodeOptions struct {
	// disable loading native addons.
	// Experimental.
	Addons *bool `field:"optional" json:"addons" yaml:"addons"`
	// allow use of addons when any permissions are set.
	// Experimental.
	AllowAddons *bool `field:"optional" json:"allowAddons" yaml:"allowAddons"`
	// allow use of child process when any permissions are set.
	// Experimental.
	AllowChildProcess *bool `field:"optional" json:"allowChildProcess" yaml:"allowChildProcess"`
	// allow permissions to read the filesystem.
	// Experimental.
	AllowFsRead *[]*string `field:"optional" json:"allowFsRead" yaml:"allowFsRead"`
	// allow permissions to write in the filesystem.
	// Experimental.
	AllowFsWrite *[]*string `field:"optional" json:"allowFsWrite" yaml:"allowFsWrite"`
	// allow use of inspector when any permissions are set.
	// Experimental.
	AllowInspector *bool `field:"optional" json:"allowInspector" yaml:"allowInspector"`
	// allow wasi when any permissions are set.
	// Experimental.
	AllowWasi *bool `field:"optional" json:"allowWasi" yaml:"allowWasi"`
	// allow worker threads when any permissions are set.
	// Experimental.
	AllowWorker *bool `field:"optional" json:"allowWorker" yaml:"allowWorker"`
	// Improve AsyncLocalStorage performance with AsyncContextFrame.
	// Experimental.
	AsyncContextFrame *bool `field:"optional" json:"asyncContextFrame" yaml:"asyncContextFrame"`
	// additional user conditions for conditional exports and imports.
	// Experimental.
	Conditions *[]*string `field:"optional" json:"conditions" yaml:"conditions"`
	// Start the V8 CPU profiler on start up, and write the CPU profile to disk before exit.
	//
	// If --cpu-prof-dir is not specified, write the profile to the current working directory.
	// Experimental.
	CpuProf *bool `field:"optional" json:"cpuProf" yaml:"cpuProf"`
	// Directory where the V8 profiles generated by --cpu-prof will be placed.
	//
	// Does not affect --prof.
	// Experimental.
	CpuProfDir *string `field:"optional" json:"cpuProfDir" yaml:"cpuProfDir"`
	// specified sampling interval in microseconds for the V8 CPU profile generated with --cpu-prof.
	//
	// (default: 1000).
	// Experimental.
	CpuProfInterval *float64 `field:"optional" json:"cpuProfInterval" yaml:"cpuProfInterval"`
	// specified file name of the V8 CPU profile generated with --cpu-prof.
	// Experimental.
	CpuProfName *string `field:"optional" json:"cpuProfName" yaml:"cpuProfName"`
	// Experimental.
	DebugArraybufferAllocations *bool `field:"optional" json:"debugArraybufferAllocations" yaml:"debugArraybufferAllocations"`
	// silence deprecation warnings.
	// Experimental.
	Deprecation *bool `field:"optional" json:"deprecation" yaml:"deprecation"`
	// set dir for all output files (default: current working directory).
	// Experimental.
	DiagnosticDir *string `field:"optional" json:"diagnosticDir" yaml:"diagnosticDir"`
	// disable Object.prototype.__proto__.
	// Experimental.
	DisableProto *string `field:"optional" json:"disableProto" yaml:"disableProto"`
	// Disable inspector thread to be listening for SIGUSR1 signal.
	// Experimental.
	DisableSigusr1 *bool `field:"optional" json:"disableSigusr1" yaml:"disableSigusr1"`
	// silence specific process warnings.
	// Experimental.
	DisableWarning *[]*string `field:"optional" json:"disableWarning" yaml:"disableWarning"`
	// Disable trap-handler-based WebAssembly bound checks.
	//
	// V8 will insert inline bound checks when compiling WebAssembly which may slow down performance.
	// Experimental.
	DisableWasmTrapHandler *bool `field:"optional" json:"disableWasmTrapHandler" yaml:"disableWasmTrapHandler"`
	// set default value of verbatim in dns.lookup. Options are 'ipv4first' (IPv4 addresses are placed before IPv6 addresses) 'ipv6first' (IPv6 addresses are placed before IPv4 addresses) 'verbatim' (addresses are in the order the DNS resolver returned).
	// Experimental.
	DnsResultOrder *string `field:"optional" json:"dnsResultOrder" yaml:"dnsResultOrder"`
	// enable FIPS crypto at startup.
	// Experimental.
	EnableFips *bool `field:"optional" json:"enableFips" yaml:"enableFips"`
	// Source Map V3 support for stack traces.
	// Experimental.
	EnableSourceMaps *bool `field:"optional" json:"enableSourceMaps" yaml:"enableSourceMaps"`
	// Treat the entrypoint as a URL.
	// Experimental.
	EntryUrl *bool `field:"optional" json:"entryUrl" yaml:"entryUrl"`
	// experimental import support for addons.
	// Experimental.
	ExperimentalAddonModules *bool `field:"optional" json:"experimentalAddonModules" yaml:"experimentalAddonModules"`
	// when ambiguous modules fail to evaluate because they contain ES module syntax, try again to evaluate them as ES modules.
	// Experimental.
	ExperimentalDetectModule *bool `field:"optional" json:"experimentalDetectModule" yaml:"experimentalDetectModule"`
	// experimental EventSource API.
	// Experimental.
	ExperimentalEventsource *bool `field:"optional" json:"experimentalEventsource" yaml:"experimentalEventsource"`
	// expose experimental Navigator API on the global scope.
	// Experimental.
	ExperimentalGlobalNavigator *bool `field:"optional" json:"experimentalGlobalNavigator" yaml:"experimentalGlobalNavigator"`
	// experimental ES Module import.meta.resolve() parentURL support.
	// Experimental.
	ExperimentalImportMetaResolve *bool `field:"optional" json:"experimentalImportMetaResolve" yaml:"experimentalImportMetaResolve"`
	// use the specified module as a custom loader.
	// Experimental.
	ExperimentalLoader *[]*string `field:"optional" json:"experimentalLoader" yaml:"experimentalLoader"`
	// Print pending top-level await.
	//
	// If --require-module is true, evaluate asynchronous graphs loaded by `require()` but do not run the microtasks, in order to to find and print top-level await in the graph.
	// Experimental.
	ExperimentalPrintRequiredTla *bool `field:"optional" json:"experimentalPrintRequiredTla" yaml:"experimentalPrintRequiredTla"`
	// experimental await keyword support in REPL.
	// Experimental.
	ExperimentalReplAwait *bool `field:"optional" json:"experimentalReplAwait" yaml:"experimentalReplAwait"`
	// Legacy alias for --require-module.
	// Experimental.
	ExperimentalRequireModule *bool `field:"optional" json:"experimentalRequireModule" yaml:"experimentalRequireModule"`
	// Experimental.
	ExperimentalShadowRealm *bool `field:"optional" json:"experimentalShadowRealm" yaml:"experimentalShadowRealm"`
	// experimental node:sqlite module.
	// Experimental.
	ExperimentalSqlite *bool `field:"optional" json:"experimentalSqlite" yaml:"experimentalSqlite"`
	// enable transformation of TypeScript-onlysyntax into JavaScript code.
	// Experimental.
	ExperimentalTransformTypes *bool `field:"optional" json:"experimentalTransformTypes" yaml:"experimentalTransformTypes"`
	// experimental ES Module support in vm module.
	// Experimental.
	ExperimentalVmModules *bool `field:"optional" json:"experimentalVmModules" yaml:"experimentalVmModules"`
	// experimental WebSocket API.
	// Experimental.
	ExperimentalWebsocket *bool `field:"optional" json:"experimentalWebsocket" yaml:"experimentalWebsocket"`
	// experimental Web Storage API.
	// Experimental.
	ExperimentalWebstorage *bool `field:"optional" json:"experimentalWebstorage" yaml:"experimentalWebstorage"`
	// hide extra information on fatal exception that causes exit.
	// Experimental.
	ExtraInfoOnFatalException *bool `field:"optional" json:"extraInfoOnFatalException" yaml:"extraInfoOnFatalException"`
	// disable checks for async_hooks.
	// Experimental.
	ForceAsyncHooksChecks *bool `field:"optional" json:"forceAsyncHooksChecks" yaml:"forceAsyncHooksChecks"`
	// disable loading non-context-aware addons.
	// Experimental.
	ForceContextAware *bool `field:"optional" json:"forceContextAware" yaml:"forceContextAware"`
	// force FIPS crypto (cannot be disabled).
	// Experimental.
	ForceFips *bool `field:"optional" json:"forceFips" yaml:"forceFips"`
	// enforces 'uncaughtException' event on Node API asynchronous callbacks.
	// Experimental.
	ForceNodeApiUncaughtExceptionsPolicy *bool `field:"optional" json:"forceNodeApiUncaughtExceptionsPolicy" yaml:"forceNodeApiUncaughtExceptionsPolicy"`
	// experimental frozen intrinsics support.
	// Experimental.
	FrozenIntrinsics *bool `field:"optional" json:"frozenIntrinsics" yaml:"frozenIntrinsics"`
	// disable global module search paths.
	// Experimental.
	GlobalSearchPaths *bool `field:"optional" json:"globalSearchPaths" yaml:"globalSearchPaths"`
	// Start the V8 heap profiler on start up, and write the heap profile to disk before exit.
	//
	// If --heap-prof-dir is not specified, write the profile to the current working directory.
	// Experimental.
	HeapProf *bool `field:"optional" json:"heapProf" yaml:"heapProf"`
	// Directory where the V8 heap profiles generated by --heap-prof will be placed.
	// Experimental.
	HeapProfDir *string `field:"optional" json:"heapProfDir" yaml:"heapProfDir"`
	// specified sampling interval in bytes for the V8 heap profile generated with --heap-prof.
	//
	// (default: 512 * 1024).
	// Experimental.
	HeapProfInterval *float64 `field:"optional" json:"heapProfInterval" yaml:"heapProfInterval"`
	// specified file name of the V8 heap profile generated with --heap-prof.
	// Experimental.
	HeapProfName *string `field:"optional" json:"heapProfName" yaml:"heapProfName"`
	// Generate heap snapshots whenever V8 is approaching the heap limit.
	//
	// No more than the specified number of heap snapshots will be generated.
	// Experimental.
	HeapsnapshotNearHeapLimit *float64 `field:"optional" json:"heapsnapshotNearHeapLimit" yaml:"heapsnapshotNearHeapLimit"`
	// Generate heap snapshot on specified signal.
	// Experimental.
	HeapsnapshotSignal *string `field:"optional" json:"heapsnapshotSignal" yaml:"heapsnapshotSignal"`
	// set ICU data load path to dir (overrides NODE_ICU_DATA) (note: linked-in ICU data is present).
	// Experimental.
	IcuDataDir *string `field:"optional" json:"icuDataDir" yaml:"icuDataDir"`
	// ES module to preload (option can be repeated).
	// Experimental.
	Import *[]*string `field:"optional" json:"import" yaml:"import"`
	// set module type for string input.
	// Experimental.
	InputType *string `field:"optional" json:"inputType" yaml:"inputType"`
	// use an insecure HTTP parser that accepts invalid HTTP headers.
	// Experimental.
	InsecureHttpParser *bool `field:"optional" json:"insecureHttpParser" yaml:"insecureHttpParser"`
	// activate inspector on host:port (default: 127.0.0.1:9229).
	// Experimental.
	Inspect *bool `field:"optional" json:"inspect" yaml:"inspect"`
	// activate inspector on host:port and break at start of user script.
	// Experimental.
	InspectBrk *bool `field:"optional" json:"inspectBrk" yaml:"inspectBrk"`
	// set host:port for inspector.
	// Experimental.
	InspectPort *float64 `field:"optional" json:"inspectPort" yaml:"inspectPort"`
	// comma separated list of destinations for inspector uid(default: stderr,http).
	// Experimental.
	InspectPublishUid *string `field:"optional" json:"inspectPublishUid" yaml:"inspectPublishUid"`
	// activate inspector on host:port and wait for debugger to be attached.
	// Experimental.
	InspectWait *bool `field:"optional" json:"inspectWait" yaml:"inspectWait"`
	// file used to persist localStorage data.
	// Experimental.
	LocalstorageFile *string `field:"optional" json:"localstorageFile" yaml:"localstorageFile"`
	// set the maximum size of HTTP headers (default: 16384 (16KB)).
	// Experimental.
	MaxHttpHeaderSize *float64 `field:"optional" json:"maxHttpHeaderSize" yaml:"maxHttpHeaderSize"`
	// set V8's max old space size as a percentage of available memory (e.g., '50%'). Takes precedence over --max-old-space-size.
	// Experimental.
	MaxOldSpaceSizePercentage *string `field:"optional" json:"maxOldSpaceSizePercentage" yaml:"maxOldSpaceSizePercentage"`
	// Disable network address family autodetection algorithm.
	// Experimental.
	NetworkFamilyAutoselection *bool `field:"optional" json:"networkFamilyAutoselection" yaml:"networkFamilyAutoselection"`
	// Sets the default value for the network family autoselection attempt timeout.
	// Experimental.
	NetworkFamilyAutoselectionAttemptTimeout *float64 `field:"optional" json:"networkFamilyAutoselectionAttemptTimeout" yaml:"networkFamilyAutoselectionAttemptTimeout"`
	// Experimental.
	NodeSnapshot *bool `field:"optional" json:"nodeSnapshot" yaml:"nodeSnapshot"`
	// load OpenSSL configuration from the specified file (overrides OPENSSL_CONF).
	// Experimental.
	OpensslConfig *string `field:"optional" json:"opensslConfig" yaml:"opensslConfig"`
	// enable OpenSSL 3.0 legacy provider.
	// Experimental.
	OpensslLegacyProvider *bool `field:"optional" json:"opensslLegacyProvider" yaml:"opensslLegacyProvider"`
	// enable OpenSSL shared configuration.
	// Experimental.
	OpensslSharedConfig *bool `field:"optional" json:"opensslSharedConfig" yaml:"opensslSharedConfig"`
	// emit pending deprecation warnings.
	// Experimental.
	PendingDeprecation *bool `field:"optional" json:"pendingDeprecation" yaml:"pendingDeprecation"`
	// enable the permission system.
	// Experimental.
	Permission *bool `field:"optional" json:"permission" yaml:"permission"`
	// preserve symbolic links when resolving.
	// Experimental.
	PreserveSymlinks *bool `field:"optional" json:"preserveSymlinks" yaml:"preserveSymlinks"`
	// preserve symbolic links when resolving the main module.
	// Experimental.
	PreserveSymlinksMain *bool `field:"optional" json:"preserveSymlinksMain" yaml:"preserveSymlinksMain"`
	// write warnings to file instead of stderr.
	// Experimental.
	RedirectWarnings *string `field:"optional" json:"redirectWarnings" yaml:"redirectWarnings"`
	// output compact single-line JSON.
	// Experimental.
	ReportCompact *bool `field:"optional" json:"reportCompact" yaml:"reportCompact"`
	// define custom report pathname.
	//
	// (default: current working directory).
	// Experimental.
	ReportDir *string `field:"optional" json:"reportDir" yaml:"reportDir"`
	// Exclude environment variables when generating report (default: false).
	// Experimental.
	ReportExcludeEnv *bool `field:"optional" json:"reportExcludeEnv" yaml:"reportExcludeEnv"`
	// exclude network interface diagnostics.
	//
	// (default: false).
	// Experimental.
	ReportExcludeNetwork *bool `field:"optional" json:"reportExcludeNetwork" yaml:"reportExcludeNetwork"`
	// define custom report file name.
	//
	// (default: YYYYMMDD.HHMMSS.PID.SEQUENCE#.txt)
	// Experimental.
	ReportFilename *string `field:"optional" json:"reportFilename" yaml:"reportFilename"`
	// generate diagnostic report on fatal (internal) errors.
	// Experimental.
	ReportOnFatalerror *bool `field:"optional" json:"reportOnFatalerror" yaml:"reportOnFatalerror"`
	// generate diagnostic report upon receiving signals.
	// Experimental.
	ReportOnSignal *bool `field:"optional" json:"reportOnSignal" yaml:"reportOnSignal"`
	// causes diagnostic report to be produced on provided signal, unsupported in Windows.
	//
	// (default: SIGUSR2).
	// Experimental.
	ReportSignal *string `field:"optional" json:"reportSignal" yaml:"reportSignal"`
	// generate diagnostic report on uncaught exceptions.
	// Experimental.
	ReportUncaughtException *bool `field:"optional" json:"reportUncaughtException" yaml:"reportUncaughtException"`
	// CommonJS module to preload (option can be repeated).
	// Experimental.
	Require *[]*string `field:"optional" json:"require" yaml:"require"`
	// Allow loading synchronous ES Modules in require().
	// Experimental.
	RequireModule *bool `field:"optional" json:"requireModule" yaml:"requireModule"`
	// total size of the OpenSSL secure heap.
	// Experimental.
	SecureHeap *float64 `field:"optional" json:"secureHeap" yaml:"secureHeap"`
	// minimum allocation size from the OpenSSL secure heap.
	// Experimental.
	SecureHeapMin *float64 `field:"optional" json:"secureHeapMin" yaml:"secureHeapMin"`
	// Path to the snapshot blob that's either the result of snapshotbuilding, or the blob that is used to restore the application state.
	// Experimental.
	SnapshotBlob *string `field:"optional" json:"snapshotBlob" yaml:"snapshotBlob"`
	// Experimental.
	StackTraceLimit *float64 `field:"optional" json:"stackTraceLimit" yaml:"stackTraceLimit"`
	// Type-stripping for TypeScript files.
	// Experimental.
	StripTypes *bool `field:"optional" json:"stripTypes" yaml:"stripTypes"`
	// the branch coverage minimum threshold.
	// Experimental.
	TestCoverageBranches *float64 `field:"optional" json:"testCoverageBranches" yaml:"testCoverageBranches"`
	// exclude files from coverage report that match this glob pattern.
	// Experimental.
	TestCoverageExclude *[]*string `field:"optional" json:"testCoverageExclude" yaml:"testCoverageExclude"`
	// the function coverage minimum threshold.
	// Experimental.
	TestCoverageFunctions *float64 `field:"optional" json:"testCoverageFunctions" yaml:"testCoverageFunctions"`
	// include files in coverage report that match this glob pattern.
	// Experimental.
	TestCoverageInclude *[]*string `field:"optional" json:"testCoverageInclude" yaml:"testCoverageInclude"`
	// the line coverage minimum threshold.
	// Experimental.
	TestCoverageLines *float64 `field:"optional" json:"testCoverageLines" yaml:"testCoverageLines"`
	// specifies the path to the global setup file.
	// Experimental.
	TestGlobalSetup *string `field:"optional" json:"testGlobalSetup" yaml:"testGlobalSetup"`
	// configures the type of test isolation used in the test runner.
	// Experimental.
	TestIsolation *string `field:"optional" json:"testIsolation" yaml:"testIsolation"`
	// run tests whose name matches this regular expression.
	// Experimental.
	TestNamePattern *[]*string `field:"optional" json:"testNamePattern" yaml:"testNamePattern"`
	// run tests with 'only' option set.
	// Experimental.
	TestOnly *bool `field:"optional" json:"testOnly" yaml:"testOnly"`
	// run tests in a random order.
	// Experimental.
	TestRandomize *bool `field:"optional" json:"testRandomize" yaml:"testRandomize"`
	// seed used to randomize test execution order.
	// Experimental.
	TestRandomSeed *float64 `field:"optional" json:"testRandomSeed" yaml:"testRandomSeed"`
	// report test output using the given reporter.
	// Experimental.
	TestReporter *[]*string `field:"optional" json:"testReporter" yaml:"testReporter"`
	// report given reporter to the given destination.
	// Experimental.
	TestReporterDestination *[]*string `field:"optional" json:"testReporterDestination" yaml:"testReporterDestination"`
	// specifies the path to the rerun state file.
	// Experimental.
	TestRerunFailures *string `field:"optional" json:"testRerunFailures" yaml:"testRerunFailures"`
	// run test at specific shard.
	// Experimental.
	TestShard *string `field:"optional" json:"testShard" yaml:"testShard"`
	// run tests whose name do not match this regular expression.
	// Experimental.
	TestSkipPattern *[]*string `field:"optional" json:"testSkipPattern" yaml:"testSkipPattern"`
	// throw an exception on deprecations.
	// Experimental.
	ThrowDeprecation *bool `field:"optional" json:"throwDeprecation" yaml:"throwDeprecation"`
	// the process title to use on startup.
	// Experimental.
	Title *string `field:"optional" json:"title" yaml:"title"`
	// use an alternative default TLS cipher list.
	// Experimental.
	TlsCipherList *string `field:"optional" json:"tlsCipherList" yaml:"tlsCipherList"`
	// log TLS decryption keys to named file for traffic analysis.
	// Experimental.
	TlsKeylog *string `field:"optional" json:"tlsKeylog" yaml:"tlsKeylog"`
	// set default TLS maximum to TLSv1.2 (default: TLSv1.3).
	// Experimental.
	TlsMaxV12 *bool `field:"optional" json:"tlsMaxV12" yaml:"tlsMaxV12"`
	// set default TLS maximum to TLSv1.3 (default: TLSv1.3).
	// Experimental.
	TlsMaxV13 *bool `field:"optional" json:"tlsMaxV13" yaml:"tlsMaxV13"`
	// set default TLS minimum to TLSv1.0 (default: TLSv1.2).
	// Experimental.
	TlsMinV10 *bool `field:"optional" json:"tlsMinV10" yaml:"tlsMinV10"`
	// set default TLS minimum to TLSv1.1 (default: TLSv1.2).
	// Experimental.
	TlsMinV11 *bool `field:"optional" json:"tlsMinV11" yaml:"tlsMinV11"`
	// set default TLS minimum to TLSv1.2 (default: TLSv1.2).
	// Experimental.
	TlsMinV12 *bool `field:"optional" json:"tlsMinV12" yaml:"tlsMinV12"`
	// set default TLS minimum to TLSv1.3 (default: TLSv1.2).
	// Experimental.
	TlsMinV13 *bool `field:"optional" json:"tlsMinV13" yaml:"tlsMinV13"`
	// show stack traces on deprecations.
	// Experimental.
	TraceDeprecation *bool `field:"optional" json:"traceDeprecation" yaml:"traceDeprecation"`
	// Print accesses to the environment variables.
	// Experimental.
	TraceEnv *bool `field:"optional" json:"traceEnv" yaml:"traceEnv"`
	// Print accesses to the environment variables and the JavaScript stack trace.
	// Experimental.
	TraceEnvJsStack *bool `field:"optional" json:"traceEnvJsStack" yaml:"traceEnvJsStack"`
	// Print accesses to the environment variables and the native stack trace.
	// Experimental.
	TraceEnvNativeStack *bool `field:"optional" json:"traceEnvNativeStack" yaml:"traceEnvNativeStack"`
	// comma separated list of trace event categories to record.
	// Experimental.
	TraceEventCategories *string `field:"optional" json:"traceEventCategories" yaml:"traceEventCategories"`
	// Template string specifying the filepath for the trace-events data, it supports ${rotation} and ${pid}.
	// Experimental.
	TraceEventFilePattern *string `field:"optional" json:"traceEventFilePattern" yaml:"traceEventFilePattern"`
	// show stack trace when an environment exits.
	// Experimental.
	TraceExit *bool `field:"optional" json:"traceExit" yaml:"traceExit"`
	// show stack traces on promise initialization and resolution.
	// Experimental.
	TracePromises *bool `field:"optional" json:"tracePromises" yaml:"tracePromises"`
	// Print access to require(esm).
	//
	// Options are 'all' (print all usage) and 'no-node-modules' (excluding usage from the node_modules folder).
	// Experimental.
	TraceRequireModule *string `field:"optional" json:"traceRequireModule" yaml:"traceRequireModule"`
	// enable printing JavaScript stacktrace on SIGINT.
	// Experimental.
	TraceSigint *bool `field:"optional" json:"traceSigint" yaml:"traceSigint"`
	// show stack trace when use of sync IO is detected after the first tick.
	// Experimental.
	TraceSyncIo *bool `field:"optional" json:"traceSyncIo" yaml:"traceSyncIo"`
	// prints TLS packet trace information to stderr.
	// Experimental.
	TraceTls *bool `field:"optional" json:"traceTls" yaml:"traceTls"`
	// show stack traces for the `throw` behind uncaught exceptions.
	// Experimental.
	TraceUncaught *bool `field:"optional" json:"traceUncaught" yaml:"traceUncaught"`
	// show stack traces on process warnings.
	// Experimental.
	TraceWarnings *bool `field:"optional" json:"traceWarnings" yaml:"traceWarnings"`
	// track heap object allocations for heap snapshots.
	// Experimental.
	TrackHeapObjects *bool `field:"optional" json:"trackHeapObjects" yaml:"trackHeapObjects"`
	// define unhandled rejections behavior.
	//
	// Options are 'strict' (always raise an error), 'throw' (raise an error unless 'unhandledRejection' hook is set), 'warn' (log a warning), 'none' (silence warnings), 'warn-with-error-code' (log a warning and set exit code 1 unless 'unhandledRejection' hook is set). (default: throw)
	// Experimental.
	UnhandledRejections *string `field:"optional" json:"unhandledRejections" yaml:"unhandledRejections"`
	// use bundled CA store (default).
	// Experimental.
	UseBundledCa *bool `field:"optional" json:"useBundledCa" yaml:"useBundledCa"`
	// parse proxy settings from HTTP_PROXY/HTTPS_PROXY/NO_PROXYenvironment variables and apply the setting in global HTTP/HTTPS clients.
	// Experimental.
	UseEnvProxy *bool `field:"optional" json:"useEnvProxy" yaml:"useEnvProxy"`
	// Map the Node.js static code to large pages. Options are 'off' (the default value, meaning do not map), 'on' (map and ignore failure, reporting it to stderr), or 'silent' (map and silently ignore failure).
	// Experimental.
	UseLargepages *string `field:"optional" json:"useLargepages" yaml:"useLargepages"`
	// use OpenSSL's default CA store.
	// Experimental.
	UseOpensslCa *bool `field:"optional" json:"useOpensslCa" yaml:"useOpensslCa"`
	// use system's CA store.
	// Experimental.
	UseSystemCa *bool `field:"optional" json:"useSystemCa" yaml:"useSystemCa"`
	// set V8's thread pool size.
	// Experimental.
	V8PoolSize *float64 `field:"optional" json:"v8PoolSize" yaml:"v8PoolSize"`
	// Experimental.
	VerifyBaseObjects *bool `field:"optional" json:"verifyBaseObjects" yaml:"verifyBaseObjects"`
	// silence all process warnings.
	// Experimental.
	Warnings *bool `field:"optional" json:"warnings" yaml:"warnings"`
	// run in watch mode.
	// Experimental.
	Watch *bool `field:"optional" json:"watch" yaml:"watch"`
	// kill signal to send to the process on watch mode restarts(default: SIGTERM).
	// Experimental.
	WatchKillSignal *string `field:"optional" json:"watchKillSignal" yaml:"watchKillSignal"`
	// path to watch.
	// Experimental.
	WatchPath *[]*string `field:"optional" json:"watchPath" yaml:"watchPath"`
	// preserve outputs on watch mode restart.
	// Experimental.
	WatchPreserveOutput *bool `field:"optional" json:"watchPreserveOutput" yaml:"watchPreserveOutput"`
	// automatically zero-fill all newly allocated Buffer instances.
	// Experimental.
	ZeroFillBuffers *bool `field:"optional" json:"zeroFillBuffers" yaml:"zeroFillBuffers"`
}

