package uvconfig


// Settings that are specific to the `uv pip` command-line interface.
//
// These values will be ignored when running commands outside the `uv pip` namespace (e.g.,
// `uv lock`, `uvx`).
// Experimental.
type PipOptions struct {
	// Include all optional dependencies.
	//
	// Only applies to `pyproject.toml`, `setup.py`, and `setup.cfg` sources.
	// Experimental.
	AllExtras *bool `field:"optional" json:"allExtras" yaml:"allExtras"`
	// Allow `uv pip sync` with empty requirements, which will clear the environment of all packages.
	// Experimental.
	AllowEmptyRequirements *bool `field:"optional" json:"allowEmptyRequirements" yaml:"allowEmptyRequirements"`
	// The style of the annotation comments included in the output file, used to indicate the source of each package.
	// Experimental.
	AnnotationStyle *string `field:"optional" json:"annotationStyle" yaml:"annotationStyle"`
	// Allow uv to modify an `EXTERNALLY-MANAGED` Python installation.
	//
	// WARNING: `--break-system-packages` is intended for use in continuous integration (CI)
	// environments, when installing into Python installations that are managed by an external
	// package manager, like `apt`. It should be used with caution, as such Python installations
	// explicitly recommend against modifications by other package managers (like uv or pip).
	// Experimental.
	BreakSystemPackages *bool `field:"optional" json:"breakSystemPackages" yaml:"breakSystemPackages"`
	// Compile Python files to bytecode after installation.
	//
	// By default, uv does not compile Python (`.py`) files to bytecode (`__pycache__/*.pyc`);
	// instead, compilation is performed lazily the first time a module is imported. For use-cases
	// in which start time is critical, such as CLI applications and Docker containers, this option
	// can be enabled to trade longer installation times for faster start times.
	//
	// When enabled, uv will process the entire site-packages directory (including packages that
	// are not being modified by the current operation) for consistency. Like pip, it will also
	// ignore errors.
	// Experimental.
	CompileBytecode *bool `field:"optional" json:"compileBytecode" yaml:"compileBytecode"`
	// Settings to pass to the [PEP 517](https://peps.python.org/pep-0517/) build backend, specified as `KEY=VALUE` pairs.
	// Experimental.
	ConfigSettings *map[string]interface{} `field:"optional" json:"configSettings" yaml:"configSettings"`
	// Settings to pass to the [PEP 517](https://peps.python.org/pep-0517/) build backend for specific packages, specified as `KEY=VALUE` pairs.
	// Experimental.
	ConfigSettingsPackage *map[string]*map[string]interface{} `field:"optional" json:"configSettingsPackage" yaml:"configSettingsPackage"`
	// The header comment to include at the top of the output file generated by `uv pip compile`.
	//
	// Used to reflect custom build scripts and commands that wrap `uv pip compile`.
	// Experimental.
	CustomCompileCommand *string `field:"optional" json:"customCompileCommand" yaml:"customCompileCommand"`
	// Pre-defined static metadata for dependencies of the project (direct or transitive).
	//
	// When
	// provided, enables the resolver to use the specified metadata instead of querying the
	// registry or building the relevant package from source.
	//
	// Metadata should be provided in adherence with the [Metadata 2.3](https://packaging.python.org/en/latest/specifications/core-metadata/)
	// standard, though only the following fields are respected:
	//
	// - `name`: The name of the package.
	// - (Optional) `version`: The version of the package. If omitted, the metadata will be applied
	// to all versions of the package.
	// - (Optional) `requires-dist`: The dependencies of the package (e.g., `werkzeug>=0.14`).
	// - (Optional) `requires-python`: The Python version required by the package (e.g., `>=3.10`).
	// - (Optional) `provides-extra`: The extras provided by the package.
	// Experimental.
	DependencyMetadata *[]*StaticMetadata `field:"optional" json:"dependencyMetadata" yaml:"dependencyMetadata"`
	// Include `--no-binary` and `--only-binary` entries in the output file generated by `uv pip compile`.
	// Experimental.
	EmitBuildOptions *bool `field:"optional" json:"emitBuildOptions" yaml:"emitBuildOptions"`
	// Include `--find-links` entries in the output file generated by `uv pip compile`.
	// Experimental.
	EmitFindLinks *bool `field:"optional" json:"emitFindLinks" yaml:"emitFindLinks"`
	// Include comment annotations indicating the index used to resolve each package (e.g., `# from https://pypi.org/simple`).
	// Experimental.
	EmitIndexAnnotation *bool `field:"optional" json:"emitIndexAnnotation" yaml:"emitIndexAnnotation"`
	// Include `--index-url` and `--extra-index-url` entries in the output file generated by `uv pip compile`.
	// Experimental.
	EmitIndexUrl *bool `field:"optional" json:"emitIndexUrl" yaml:"emitIndexUrl"`
	// Whether to emit a marker string indicating the conditions under which the set of pinned dependencies is valid.
	//
	// The pinned dependencies may be valid even when the marker expression is
	// false, but when the expression is true, the requirements are known to
	// be correct.
	// Experimental.
	EmitMarkerExpression *bool `field:"optional" json:"emitMarkerExpression" yaml:"emitMarkerExpression"`
	// Limit candidate packages to those that were uploaded prior to a given point in time.
	//
	// Accepts a superset of [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339.html) (e.g.,
	// `2006-12-02T02:07:43Z`). A full timestamp is required to ensure that the resolver will
	// behave consistently across timezones.
	// Experimental.
	ExcludeNewer *string `field:"optional" json:"excludeNewer" yaml:"excludeNewer"`
	// Limit candidate packages for specific packages to those that were uploaded prior to the given date.
	//
	// Accepts package-date pairs in a dictionary format.
	// Experimental.
	ExcludeNewerPackage *map[string]*string `field:"optional" json:"excludeNewerPackage" yaml:"excludeNewerPackage"`
	// Include optional dependencies from the specified extra; may be provided more than once.
	//
	// Only applies to `pyproject.toml`, `setup.py`, and `setup.cfg` sources.
	// Experimental.
	Extra *[]*string `field:"optional" json:"extra" yaml:"extra"`
	// Additional build dependencies for packages.
	//
	// This allows extending the PEP 517 build environment for the project's dependencies with
	// additional packages. This is useful for packages that assume the presence of packages like
	// `pip`, and do not declare them as build dependencies.
	// Experimental.
	ExtraBuildDependencies *map[string]*[]interface{} `field:"optional" json:"extraBuildDependencies" yaml:"extraBuildDependencies"`
	// Extra environment variables to set when building certain packages.
	//
	// Environment variables will be added to the environment when building the
	// specified packages.
	// Experimental.
	ExtraBuildVariables *map[string]*map[string]*string `field:"optional" json:"extraBuildVariables" yaml:"extraBuildVariables"`
	// Extra URLs of package indexes to use, in addition to `--index-url`.
	//
	// Accepts either a repository compliant with [PEP 503](https://peps.python.org/pep-0503/)
	// (the simple repository API), or a local directory laid out in the same format.
	//
	// All indexes provided via this flag take priority over the index specified by
	// [`index_url`](#index-url). When multiple indexes are provided, earlier values take priority.
	//
	// To control uv's resolution strategy when multiple indexes are present, see
	// [`index_strategy`](#index-strategy).
	// Experimental.
	ExtraIndexUrl *[]*string `field:"optional" json:"extraIndexUrl" yaml:"extraIndexUrl"`
	// Locations to search for candidate distributions, in addition to those found in the registry indexes.
	//
	// If a path, the target must be a directory that contains packages as wheel files (`.whl`) or
	// source distributions (e.g., `.tar.gz` or `.zip`) at the top level.
	//
	// If a URL, the page must contain a flat list of links to package files adhering to the
	// formats described above.
	// Experimental.
	FindLinks *[]*string `field:"optional" json:"findLinks" yaml:"findLinks"`
	// The strategy to use when selecting multiple versions of a given package across Python versions and platforms.
	//
	// By default, uv will optimize for selecting the latest version of each package for each
	// supported Python version (`requires-python`), while minimizing the number of selected
	// versions across platforms.
	//
	// Under `fewest`, uv will minimize the number of selected versions for each package,
	// preferring older versions that are compatible with a wider range of supported Python
	// versions or platforms.
	// Experimental.
	ForkStrategy *string `field:"optional" json:"forkStrategy" yaml:"forkStrategy"`
	// Include distribution hashes in the output file.
	// Experimental.
	GenerateHashes *bool `field:"optional" json:"generateHashes" yaml:"generateHashes"`
	// Include the following dependency groups.
	// Experimental.
	Group *[]*PipGroupName `field:"optional" json:"group" yaml:"group"`
	// The strategy to use when resolving against multiple index URLs.
	//
	// By default, uv will stop at the first index on which a given package is available, and
	// limit resolutions to those present on that first index (`first-index`). This prevents
	// "dependency confusion" attacks, whereby an attacker can upload a malicious package under the
	// same name to an alternate index.
	// Experimental.
	IndexStrategy *string `field:"optional" json:"indexStrategy" yaml:"indexStrategy"`
	// The URL of the Python package index (by default: <https://pypi.org/simple>).
	//
	// Accepts either a repository compliant with [PEP 503](https://peps.python.org/pep-0503/)
	// (the simple repository API), or a local directory laid out in the same format.
	//
	// The index provided by this setting is given lower priority than any indexes specified via
	// [`extra_index_url`](#extra-index-url).
	// Experimental.
	IndexUrl *string `field:"optional" json:"indexUrl" yaml:"indexUrl"`
	// Attempt to use `keyring` for authentication for index URLs.
	//
	// At present, only `--keyring-provider subprocess` is supported, which configures uv to
	// use the `keyring` CLI to handle authentication.
	// Experimental.
	KeyringProvider *string `field:"optional" json:"keyringProvider" yaml:"keyringProvider"`
	// The method to use when installing packages from the global cache.
	//
	// Defaults to `clone` (also known as Copy-on-Write) on macOS, and `hardlink` on Linux and
	// Windows.
	//
	// WARNING: The use of symlink link mode is discouraged, as they create tight coupling between
	// the cache and the target environment. For example, clearing the cache (`uv cache clean`)
	// will break all installed packages by way of removing the underlying source files. Use
	// symlinks with caution.
	// Default: clone` (also known as Copy-on-Write) on macOS, and `hardlink` on Linux and.
	//
	// Experimental.
	LinkMode *string `field:"optional" json:"linkMode" yaml:"linkMode"`
	// Exclude comment annotations indicating the source of each package from the output file generated by `uv pip compile`.
	// Experimental.
	NoAnnotate *bool `field:"optional" json:"noAnnotate" yaml:"noAnnotate"`
	// Don't install pre-built wheels.
	//
	// The given packages will be built and installed from source. The resolver will still use
	// pre-built wheels to extract package metadata, if available.
	//
	// Multiple packages may be provided. Disable binaries for all packages with `:all:`.
	// Clear previously specified packages with `:none:`.
	// Experimental.
	NoBinary *[]*string `field:"optional" json:"noBinary" yaml:"noBinary"`
	// Don't build source distributions.
	//
	// When enabled, resolving will not run arbitrary Python code. The cached wheels of
	// already-built source distributions will be reused, but operations that require building
	// distributions will exit with an error.
	//
	// Alias for `--only-binary :all:`.
	// Experimental.
	NoBuild *bool `field:"optional" json:"noBuild" yaml:"noBuild"`
	// Disable isolation when building source distributions.
	//
	// Assumes that build dependencies specified by [PEP 518](https://peps.python.org/pep-0518/)
	// are already installed.
	// Experimental.
	NoBuildIsolation *bool `field:"optional" json:"noBuildIsolation" yaml:"noBuildIsolation"`
	// Disable isolation when building source distributions for a specific package.
	//
	// Assumes that the packages' build dependencies specified by [PEP 518](https://peps.python.org/pep-0518/)
	// are already installed.
	// Experimental.
	NoBuildIsolationPackage *[]*string `field:"optional" json:"noBuildIsolationPackage" yaml:"noBuildIsolationPackage"`
	// Ignore package dependencies, instead only add those packages explicitly listed on the command line to the resulting requirements file.
	// Experimental.
	NoDeps *bool `field:"optional" json:"noDeps" yaml:"noDeps"`
	// Specify a package to omit from the output resolution.
	//
	// Its dependencies will still be
	// included in the resolution. Equivalent to pip-compile's `--unsafe-package` option.
	// Experimental.
	NoEmitPackage *[]*string `field:"optional" json:"noEmitPackage" yaml:"noEmitPackage"`
	// Exclude the specified optional dependencies if `all-extras` is supplied.
	// Experimental.
	NoExtra *[]*string `field:"optional" json:"noExtra" yaml:"noExtra"`
	// Exclude the comment header at the top of output file generated by `uv pip compile`.
	// Experimental.
	NoHeader *bool `field:"optional" json:"noHeader" yaml:"noHeader"`
	// Ignore all registry indexes (e.g., PyPI), instead relying on direct URL dependencies and those provided via `--find-links`.
	// Experimental.
	NoIndex *bool `field:"optional" json:"noIndex" yaml:"noIndex"`
	// Ignore the `tool.uv.sources` table when resolving dependencies. Used to lock against the standards-compliant, publishable package metadata, as opposed to using any local or Git sources.
	// Experimental.
	NoSources *bool `field:"optional" json:"noSources" yaml:"noSources"`
	// Include extras in the output file.
	//
	// By default, uv strips extras, as any packages pulled in by the extras are already included
	// as dependencies in the output file directly. Further, output files generated with
	// `--no-strip-extras` cannot be used as constraints files in `install` and `sync` invocations.
	// Experimental.
	NoStripExtras *bool `field:"optional" json:"noStripExtras" yaml:"noStripExtras"`
	// Include environment markers in the output file generated by `uv pip compile`.
	//
	// By default, uv strips environment markers, as the resolution generated by `compile` is
	// only guaranteed to be correct for the target environment.
	// Experimental.
	NoStripMarkers *bool `field:"optional" json:"noStripMarkers" yaml:"noStripMarkers"`
	// Only use pre-built wheels; don't build source distributions.
	//
	// When enabled, resolving will not run code from the given packages. The cached wheels of already-built
	// source distributions will be reused, but operations that require building distributions will
	// exit with an error.
	//
	// Multiple packages may be provided. Disable binaries for all packages with `:all:`.
	// Clear previously specified packages with `:none:`.
	// Experimental.
	OnlyBinary *[]*string `field:"optional" json:"onlyBinary" yaml:"onlyBinary"`
	// Write the requirements generated by `uv pip compile` to the given `requirements.txt` file.
	//
	// If the file already exists, the existing versions will be preferred when resolving
	// dependencies, unless `--upgrade` is also specified.
	// Experimental.
	OutputFile *string `field:"optional" json:"outputFile" yaml:"outputFile"`
	// Install packages into `lib`, `bin`, and other top-level folders under the specified directory, as if a virtual environment were present at that location.
	//
	// In general, prefer the use of `--python` to install into an alternate environment, as
	// scripts and other artifacts installed via `--prefix` will reference the installing
	// interpreter, rather than any interpreter added to the `--prefix` directory, rendering them
	// non-portable.
	// Experimental.
	Prefix *string `field:"optional" json:"prefix" yaml:"prefix"`
	// The strategy to use when considering pre-release versions.
	//
	// By default, uv will accept pre-releases for packages that _only_ publish pre-releases,
	// along with first-party requirements that contain an explicit pre-release marker in the
	// declared specifiers (`if-necessary-or-explicit`).
	// Experimental.
	Prerelease *string `field:"optional" json:"prerelease" yaml:"prerelease"`
	// The Python interpreter into which packages should be installed.
	//
	// By default, uv installs into the virtual environment in the current working directory or
	// any parent directory. The `--python` option allows you to specify a different interpreter,
	// which is intended for use in continuous integration (CI) environments or other automated
	// workflows.
	//
	// Supported formats:
	// - `3.10` looks for an installed Python 3.10 in the registry on Windows (see
	// `py --list-paths`), or `python3.10` on Linux and macOS.
	// - `python3.10` or `python.exe` looks for a binary with the given name in `PATH`.
	// - `/home/ferris/.local/bin/python3.10` uses the exact Python at the given path.
	// Experimental.
	Python *string `field:"optional" json:"python" yaml:"python"`
	// The platform for which requirements should be resolved.
	//
	// Represented as a "target triple", a string that describes the target platform in terms of
	// its CPU, vendor, and operating system name, like `x86_64-unknown-linux-gnu` or
	// `aarch64-apple-darwin`.
	// Experimental.
	PythonPlatform *string `field:"optional" json:"pythonPlatform" yaml:"pythonPlatform"`
	// The minimum Python version that should be supported by the resolved requirements (e.g., `3.8` or `3.8.17`).
	//
	// If a patch version is omitted, the minimum patch version is assumed. For example, `3.8` is
	// mapped to `3.8.0`.
	// Experimental.
	PythonVersion *string `field:"optional" json:"pythonVersion" yaml:"pythonVersion"`
	// Reinstall all packages, regardless of whether they're already installed.
	//
	// Implies `refresh`.
	// Experimental.
	Reinstall *bool `field:"optional" json:"reinstall" yaml:"reinstall"`
	// Reinstall a specific package, regardless of whether it's already installed.
	//
	// Implies
	// `refresh-package`.
	// Experimental.
	ReinstallPackage *[]*string `field:"optional" json:"reinstallPackage" yaml:"reinstallPackage"`
	// Require a matching hash for each requirement.
	//
	// Hash-checking mode is all or nothing. If enabled, _all_ requirements must be provided
	// with a corresponding hash or set of hashes. Additionally, if enabled, _all_ requirements
	// must either be pinned to exact versions (e.g., `==1.0.0`), or be specified via direct URL.
	//
	// Hash-checking mode introduces a number of additional constraints:
	//
	// - Git dependencies are not supported.
	// - Editable installations are not supported.
	// - Local dependencies are not supported, unless they point to a specific wheel (`.whl`) or
	// source archive (`.zip`, `.tar.gz`), as opposed to a directory.
	// Experimental.
	RequireHashes *bool `field:"optional" json:"requireHashes" yaml:"requireHashes"`
	// The strategy to use when selecting between the different compatible versions for a given package requirement.
	//
	// By default, uv will use the latest compatible version of each package (`highest`).
	// Experimental.
	Resolution *string `field:"optional" json:"resolution" yaml:"resolution"`
	// Validate the Python environment, to detect packages with missing dependencies and other issues.
	// Experimental.
	Strict *bool `field:"optional" json:"strict" yaml:"strict"`
	// Install packages into the system Python environment.
	//
	// By default, uv installs into the virtual environment in the current working directory or
	// any parent directory. The `--system` option instructs uv to instead use the first Python
	// found in the system `PATH`.
	//
	// WARNING: `--system` is intended for use in continuous integration (CI) environments and
	// should be used with caution, as it can modify the system Python installation.
	// Experimental.
	System *bool `field:"optional" json:"system" yaml:"system"`
	// Install packages into the specified directory, rather than into the virtual or system Python environment.
	//
	// The packages will be installed at the top-level of the directory.
	// Experimental.
	Target *string `field:"optional" json:"target" yaml:"target"`
	// The backend to use when fetching packages in the PyTorch ecosystem.
	//
	// When set, uv will ignore the configured index URLs for packages in the PyTorch ecosystem,
	// and will instead use the defined backend.
	//
	// For example, when set to `cpu`, uv will use the CPU-only PyTorch index; when set to `cu126`,
	// uv will use the PyTorch index for CUDA 12.6.
	//
	// The `auto` mode will attempt to detect the appropriate PyTorch index based on the currently
	// installed CUDA drivers.
	//
	// This option is in preview and may change in any future release.
	// Experimental.
	TorchBackend *string `field:"optional" json:"torchBackend" yaml:"torchBackend"`
	// Perform a universal resolution, attempting to generate a single `requirements.txt` output file that is compatible with all operating systems, architectures, and Python implementations.
	//
	// In universal mode, the current Python version (or user-provided `--python-version`) will be
	// treated as a lower bound. For example, `--universal --python-version 3.7` would produce a
	// universal resolution for Python 3.7 and later.
	// Experimental.
	Universal *bool `field:"optional" json:"universal" yaml:"universal"`
	// Allow package upgrades, ignoring pinned versions in any existing output file.
	// Experimental.
	Upgrade *bool `field:"optional" json:"upgrade" yaml:"upgrade"`
	// Allow upgrades for a specific package, ignoring pinned versions in any existing output file.
	//
	// Accepts both standalone package names (`ruff`) and version specifiers (`ruff<0.5.0`).
	// Experimental.
	UpgradePackage *[]*string `field:"optional" json:"upgradePackage" yaml:"upgradePackage"`
	// Validate any hashes provided in the requirements file.
	//
	// Unlike `--require-hashes`, `--verify-hashes` does not require that all requirements have
	// hashes; instead, it will limit itself to verifying the hashes of those requirements that do
	// include them.
	// Experimental.
	VerifyHashes *bool `field:"optional" json:"verifyHashes" yaml:"verifyHashes"`
}

